apiVersion: v1
kind: Service
metadata:
  name: pb-rstlserver
  labels:
    app: pb-rstlserver
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: pb-rstlserver
