apiVersion: v1
kind: Service
metadata:
  name: pb-web-service
  labels:
    app: pb-web-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: pb-webserver
